### ISSUE TITLE
Alias action does not use URL from Deploy action

### ISSUE THREAD

**Issue by mxstbr** [actions/zeit-now#3]
See this run: https://github.com/mxstbr/mxstbr.com/runs/52646048

The “Deploy” action deployed `https://workspace-whimvwiq0.now.sh`, which is the correct deploy with the new code, but then the “Alias” action aliased a totally different deploy without the new code (`mxstbrcom-86jxwz6is.now.sh`) to the alias URL.

**Comment by tedmiston** [comment]
It seems like this might have been fixed, or at least, I'm not experiencing it on my repo with deploy and alias steps.  I'm using the master tag in my actions FWIW.

Deploy - https://github.com/tedmiston/qcbrunch/runs/64691068

```
### STARTED Deploy 23:03:43Z
...
https://workspace-fgzsgg42a.now.sh
�[2K�[G> Success! Deployment ready [7s]

### SUCCEEDED Deploy 23:04:21Z (37.651s)
```

Alias - https://github.com/tedmiston/qcbrunch/runs/64691201

```
### STARTED Alias 23:04:21Z
...
> Assigning alias qcbrunch.com to deployment workspace-fgzsgg42a.now.sh
�[2K�[G> Assigning alias www.qcbrunch.com to deployment workspace-fgzsgg42a.now.sh
> Success! qcbrunch.com now points to workspace-fgzsgg42a.now.sh [2s]
> Success! www.qcbrunch.com now points to workspace-fgzsgg42a.now.sh [4s]
�[2K�[G

### SUCCEEDED Alias 23:04:26Z (5.527s)
```

**Comment by mxstbr** [comment]
Cool! I switched to github.com/primer/deploy as a more complete solution, which also does aliasing with branch names on PR 👍
